config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  root 'leave_events#index'
  resources :leave_events
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/leave_event.rb
class LeaveEvent < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/leave_events_controller.rb
class LeaveEventsController < ApplicationController
  before_action :set_leave_event, only: [:show, :edit, :update, :destroy]

  # GET /leave_events
  # GET /leave_events.json
  def index
    @leave_events = LeaveEvent.all
  end

  # GET /leave_events/1
  # GET /leave_events/1.json
  def show
  end

  # GET /leave_events/new
  def new
    @leave_event = LeaveEvent.new
  end

  # GET /leave_events/1/edit
  def edit
  end

  # POST /leave_events
  # POST /leave_events.json
  def create
    @leave_event = LeaveEvent.new(leave_event_params)

    respond_to do |format|
      if @leave_event.save
        format.html { redirect_to @leave_event, notice: 'Leave event was successfully created.' }
        format.json { render :show, status: :created, location: @leave_event }
      else
        format.html { render :new }
        format.json { render json: @leave_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leave_events/1
  # PATCH/PUT /leave_events/1.json
  def update
    respond_to do |format|
      if @leave_event.update(leave_event_params)
        format.html { redirect_to @leave_event, notice: 'Leave event was successfully updated.' }
        format.json { render :show, status: :ok, location: @leave_event }
      else
        format.html { render :edit }
        format.json { render json: @leave_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leave_events/1
  # DELETE /leave_events/1.json
  def destroy
    @leave_event.destroy
    respond_to do |format|
      format.html { redirect_to leave_events_url, notice: 'Leave event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_leave_event
      @leave_event = LeaveEvent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def leave_event_params
      params.require(:leave_event).permit(:start_time, :end_time, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leave_events_helper.rb
module LeaveEventsHelper
end

app/views/common/_alert.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/common/_navbar.html.erb
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
      <div class="sidebar-sticky">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" href="#">
              <span data-feather="home"></span>
             <h3><strong>Dashboard</strong></h3> <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file"></span>
              Employees
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="shopping-cart"></span>
              Leave Type
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="users"></span>
              Leave Management
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="bar-chart-2"></span>
              Leave History
            </a>
          </li>
        </ul>        
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LmsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
		<%= link_to 'Leave Management System',leave_events_path, class:'navbar-brand col-sm-3 col-md-2 mr-0' %>

		<input class="form-control form-control-dark w-100 col-md-6" type="text" placeholder="Search" aria-label="Search">
		<ul class="navbar-nav px-1">
			<li class="nav-item text-nowrap">
			<%= link_to 'Invite', new_user_invitation_path, class: 'nav-link' %>
			</li>
		</ul>
		<ul class="navbar-nav px-3">
			<li class="nav-item text-nowrap">
			
			<% if user_signed_in? %>
				<%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
			<% else %>
				<%= link_to 'login', new_user_session_path, class: 'nav-link' %>
			<% end %>	
			</li>
		</ul>
	</nav>
	
	<%# Alerts %>
	
		<%= render 'common/alert' %>
		
	<div class="container-fluid">
  <div class="row">
    <%= render 'common/navbar' %>

	<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
		<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
			<h1 class="h2">Dashboard</h1>
			<div class="btn-toolbar mb-2 mb-md-0">
				<div class="btn-group mr-2">
					<%# <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
					<button type="button" class="btn btn-sm btn-outline-secondary">Export</button> %>
				</div>
				<%# <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
					<span data-feather="calendar"></span>
					This week
				</button> %>
			</div>
		</div>
		
		<%= yield %>		
	</main>
  </div>
</div>	
   
		
  </body>
</html>

app/views/leave_events/_form.html.slim
= form_for @leave_event do |f|
  - if @leave_event.errors.any?
    #error_explanation
      h2 = "#{pluralize(@leave_event.errors.count, "error")} prohibited this leave_event from being saved:"
      ul
        - @leave_event.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :start_time
    = f.datetime_select :start_time
  .field
    = f.label :end_time
    = f.datetime_select :end_time
  .field
    = f.label :description
    = f.text_area :description
  .actions = f.submit

app/views/leave_events/edit.html.slim
h1 Editing leave_event

== render 'form'

=> link_to 'Show', @leave_event
'|
=< link_to 'Back', leave_events_path

app/views/leave_events/index.html.slim
h1 Listing leave_events

table
  thead
    tr
      th Start time
      th End time
      th Description
      th 
      th Action
      th

  tbody
    - @leave_events.each do |leave_event|
      tr
        td = leave_event.start_time
        td = leave_event.end_time
        td = leave_event.description
        td = link_to 'Show', leave_event
        td = link_to 'Edit', edit_leave_event_path(leave_event)
        td = link_to 'Destroy', leave_event, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Leave event', new_leave_event_path

app/views/leave_events/new.html.slim
h1 New leave_event

== render 'form'

= link_to 'Back', leave_events_path

app/views/leave_events/show.html.slim
p#notice = notice

p
  strong Start time:
  = @leave_event.start_time
p
  strong End time:
  = @leave_event.end_time
p
  strong Description:
  = @leave_event.description

=> link_to 'Edit', edit_leave_event_path(@leave_event)
'|
=< link_to 'Back', leave_events_path

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>